services:
  backend:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/logitrack_db?currentSchema=logitrack
      SPRING_DATASOURCE_USERNAME: postgres.cddszmuoujubgfyfefvl
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Bogota
      - TZ=America/Bogota
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: